#!/bin/sh
# shellcheck disable=SC1091
. _lib.sh

if ! spark > /dev/null 2>&1; then
  echo "You need 'spark' installed and in your PATH to use this." >&2
  exit 1
fi

pretty_date() {
  date -j -f "$DATE_FORMAT" "$1" +'%F %T'
}

process() {
  # shellcheck disable=SC2039
  local user="$1" repo="$2" data dates points first_date last_date first last
  if ! grep -e "$user $repo" "$STARS" > /dev/null 2>&1; then
    echo "No data found for $user $repo" >&2
    return 1
  fi
  data="$(grep "$user $repo" "$STARS")"
  dates="$(echo "$data" | awk '{print $1}')"
  points="$(echo "$data" | awk '{print $4}')"
  first_date="$(pretty_date "$(echo "$dates" | head -n1)")"
  last_date="$(pretty_date "$(echo "$dates" | tail -n1)")"
  first="$(echo "$points" | head -n1)"
  last="$(echo "$points" | tail -n1)"
  printf "\n\033[1m%s/%s\e[0m\n\e[90m(%s) %s - %s (%s)\e[0m\n" \
    "$user" "$repo" "$first_date" "$first" "$last" "$last_date"
  echo "$data" | awk '{print $4}' | awk '!x[$0]++' | spark
}

if [ $# -eq 2 ]; then
  process "$1" "$2"
else
  grep -e "^\w" "$REPOS" | while read -r user repo; do
    process "$user" "$repo"
  done
fi
