#!/bin/bash
api() {
  test -z "$GITHUB_TOKEN" && curl -s "$1"
  test -n "$GITHUB_TOKEN" &&
    curl -H "Authorization: Bearer $GITHUB_TOKEN" -s "$1"
}

fetch_info() {
  api "https://api.github.com/repos/$1/$2" |
    sed -n 's/"stargazers_count": \([0-9]*\),$/\1/p' |
    tr -d '[:space:]'
}

local_info() {
  test -s stars || return 0
  grep -e "$1\s*$2" stars |
    awk '{print $3}'
}

process() {
  local user repo current_stars previous_stars
  user="$1"
  repo="$2"
  current_stars="$(fetch_info "$user" "$repo")"
  previous_stars="$(local_info "$user" "$repo")"
  test -z "$previous_stars" && previous_stars="0"
  test -z "$current_stars" && echo "Failed to get current stars." && exit 1
  test "$current_stars" != "$previous_stars" &&
    echo "$user/$repo from $previous_stars to $current_stars stars"
  if test -s stars && grep "$user $repo" stars &> /dev/null; then
    sed -i'' -e "s/$user $repo [0-9]*/$user $repo $current_stars/" stars
  else
    echo "$user $repo $current_stars" >> stars
  fi
}

grep -e "^\w" repos | while read -r user repo; do
  process "$user" "$repo"
done
